
#ifndef Capacitor_h
#define Capacitor_h
#define eps0 8.854e-12

class Capacitor {
    public:
    // A is the surface of the capacitor, s the distance, epsr the relative permettivity of the dielectric inside
    Capacitor(); //Default Constructor, all parameters are zero
    Capacitor(double A, double s, double epsr); //constructor
    Capacitor(Capacitor& Cond); //copyconstructor
    ~Capacitor(); //destructor

    //redefine the two operators
    Capacitor operator+(const Capacitor& C) const; //series sum
    Capacitor operator||(const Capacitor& C) const; //parallel sum
    void operator=(const Capacitor& C); //copy operator

    //getters
    double getA() const;
    double getS() const;
    double getEpsr() const;
    double getC() const;

    //setters, if used on a condensator generated by + or ||, it will not give the equivalent Capacitance anymore
    void setA(double A); 
    void setS(double s);
    void setEpsr(double Epsr);
    void setC(double Cond); //Using this setter creates a discordance between A,s,epsr and C

    private:

    //if a condensator is generated by + or || will have all 0 but C, making an irrealistic condensator.
    double epsr_=.0, A_=.0, s_=.0, C=.0;
};
#endif